### PR TITLE
Styling updates & mobile fixes 

### PR DESCRIPTION
**Pull request by GFLEMING133**
Styling updates necessary for website to go live on new domain

### CODE REVIEW

**Comment by sorianog** [comment]
@GFLEMING133 Could get another screenshot of a mobile view with the changes in this PR? Also, would be nice to change the title of the PR to be a more descriptive summary. I'm glad you provided a detailed description though! 👍🏻

**Comment by GFLEMING133** [comment]
Here's another screenshot, of the homepage:

**Comment by GFLEMING133** [comment]
Here's another screenshot, of the homepage:
image

**Comment by sorianog** [comment]
Resolves #18 and #19

**Pull request merged**
